[workspace]

members = [
    "piet",
    "piet-cairo",
    "piet-common",
    "piet-direct2d",
    "piet-skia",
    "piet-test",
    "piet-web",
    "piet-web/examples/basic",
    "piet-svg"
]

default-members = [
    "piet",
    "piet-common",
    "piet-test",
    "piet-web",
    "piet-web/examples/basic",
    "piet-svg"
]
